name: "release"
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/ci.yml
  luarocks-upload:
    needs: test
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          detailed_description: |
            Find the enemy and replace them with dark power
          dependencies: |
            plenary.nvim
          license: "mit"
