name: "release"
on:
  push:
    tags:
      - 'v*'
  pull_request:
jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          detailed_description: |
            Find the enemy and replace them with dark power
          dependencies: |
            plenary.nvim
          license: "mit"
